### ISSUE TITLE
Sviluppo gem per autenticazione SPID su Ruby on Rails

### ISSUE THREAD

**Issue by alranel** [italia/spid-rails#1]
Ci sono due strade per implementare un plugin per Django:

1. usare un middleware come Shibboleth
2. implementare tutto direttamente nel plugin

La prima soluzione è più semplice ed è preferibile.
Per i dettagli sulle due possibili soluzioni si vedano le considerazioni scritte nell'analoga [issue per SPID-Django](https://github.com/italia/spid-django/issues/1).

Per integrare meccanismi di autenticazione su Ruby on Rails si usa preferibilmente [Devise](https://github.com/plataformatec/devise), che fornisce uno stack MVP completo con tutte le funzionalità generalmente richieste da una web application. A sua volta Devise può basarsi su un database locale oppure su altri meccanismi di autenticazione attraverso l'integrazione con [OmniAuth](https://github.com/omniauth/omniauth), libreria che fornisce un layer di astrazione per poter usare una grande quantità di [provider e protocolli](https://github.com/omniauth/omniauth/wiki/List-of-Strategies).

Probabilmente in entrambe le soluzioni sopra indicate conviene lavorare con Devise, e forse anche con OmniAuth?

Link utili:
* https://github.com/omniauth/omniauth-saml (non è direttamente utilizzabile con SPID perché nel sistema non abbiamo un unico Identity Provider, e quindi non abbiamo un unico URL SSO da configurare in OmniAuth)
* https://github.com/salsify/omniauth-multi-provider
* https://github.com/mkdynamic/omniauth-facebook
* https://github.com/mkdynamic/omniauth-facebook/blob/master/example/app.rb (come mostrare il bottone SPID da Sinatra - tuttavia Devise sembra una soluzione migliore in un'ottica plug and play)

Per una maggiore manutenibilità l'ideale sarebbe evitare fork di progetti già esistenti, come quelli qui citati, ma sarebbe meglio costruire un layer che li usa senza modificarli.

**Comment by descovi** [comment]
Qui per ora si è lavorato appoggiandosi sulla gemma ruby-saml: https://github.com/rubynetti/spid-rails/

Nel readme della gemma è possibile ulteriori indicazioni e qui vedere la roadmap:
https://github.com/rubynetti/spid-rails/projects/1

Abbiamo più avanti intenzione di rendere il tutto facilmente compatibile con devise perché è una gemma che usiamo in generale per gestire il login/logout delle utenze.

**Comment by descovi** [comment]
Ciao ci sono novità a riguardo?
