### ISSUE TITLE
ModuleNotFoundError: No module named 'onelogin.saml2'

### ISSUE THREAD

**Issue by fauriemma** [italia/spid-rails#27]
Buongiorno
stiamo implementato l’autenticazione SPID per il portale di una pubblica amministrazione di Napoli, ma purtroppo riscontriamo un problema in fase di start.
 
Ci viene richiesto un modulo che non riusciamo a trovare “ModuleNotFoundError: No module named 'onelogin.saml2'”
 
Se proviamo ad installare il python3-saml otteniamo il seguente messaggio d'errore:

Running setup.py install for xmlsec ...     Running command /usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-5mqwlt6s/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9icckgk3/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_ext
    *********************************************************************************
    Could not find xmlsec1 config. Are libxmlsec1-dev and pkg-config installed?
    *********************************************************************************
error

Potrebbe darci qualche indicazione in merito?

**Comment by davidlibrera** [comment]
Ciao!

Non mi torna tanto l'errore che è stato aperto. Stai parlando di python3-saml, ma questa è l'implementazione in linguaggio ruby di SPID.

Potresti fornirmi gli step che hai seguito?

**Comment by fauriemma** [comment]
Perdonami, 
L’url per la segnalazione mi è stato fornito dallo sviluppatore che segue SAP-Spid per Python e non avevo notato che mi portava sul progetto per ruby.

Chiudi pure l’issue vado a riaprirlo nella sezione giusta.

Grazie e scusa ancora

**Comment by descovi** [comment]
Chiudo
