### ISSUE TITLE
Modificare config.default_relay_state_path su spid-rails

### ISSUE THREAD

**Issue by Jeanluc74** [italia/spid-rails#28]
Buongiorno,

per prima cosa complimenti e grazie per il lavoro fatto con la gem.

Sto implementando Spid, mi piacerebbe capire come poter customizzare le configurazioni che sono offerte dalla gem di cui spid-rails è un wrapper ossia spid-ruby, ad esempio il default_relay_state_path.

Ovviamente ho tentato con la sintassi indicata su spid-ruby

Spid.configure do |config|
  #nel mio caso
  config.default_relay_state_path = "/home"
end

senza riuscire, continuo a ricevere il valore di default "/". 

Mi sareste molto d'aiuto.

Grazie,

Gian Luca

**Comment by Jeanluc74** [comment]
Tra l'altro intervenire sulla configurazione di spid-ruby darebbe la possibilità anche di specificare gli AttributeConsumingService.

**Comment by Jeanluc74** [comment]
(Perdonate se integro il ticket con le mie prove, cerco di trovare o agevolare una soluzione) Ho tentato di inserire un initializer sul modello di quanto fatto da voi sul test dummy https://github.com/italia/spid-rails/tree/master/test/dummy/config/initializers/spid.rb ma continua a non funzionare come mi aspetterei:

Traceback (most recent call last):
...
/home/decidim/test_spid3/config/initializers/spid.rb:1:in `<top (required)>': undefined method `configure' for Spid:Module (NoMethodError)

è come se non avesse possibilità di modificare i parametri di configurazione di una gem (spid-ruby) che è parte di un'altra gem (spid-rails) che è importata nel mio progetto di test, il che evidentemente potrebbe avere una logica.

Il tentativo di modifica del valore di default di @default_relay_state_path su https://github.com/italia/spid-ruby/blob/master/lib/spid/configuration.rb non è stato più fortunato.

**Comment by davidlibrera** [comment]
@Jeanluc74 non sono riuscito a replicare l'errore riguardo la configurazione.
Accedento alla console riesco sia a lanciare il metodo `Spid.configure` che riceve il configuratore da settare, sia la configuration stessa tramite `Spid.configuration`.

Porebbe indicarmi la versione di spid-ruby e spid-rails installata nella macchina?

Ad ogni modo la configurazione è una sorta di Singleton, quindi è possibile configurarlo in qualunque progetto rails.

**Comment by Jeanluc74** [comment]
Il problema era collegato alla issue #29. Risolto il problema principale su quella issue ora non si manifesta più. Chiudo questa issue, grazie.
