### ISSUE TITLE
Validazioni su spid-saml-check/spid-validator

### ISSUE THREAD

**Issue by Jeanluc74** [italia/spid-rails#31]
Buongiorno,

sperando di non risultare troppo noioso accodo un'ulteriore questione.
Ho appena terminato di effettuare i 104 test previsti dal tool in oggetto e purtroppo circa la metà delle validazioni non vanno a buon fine.
La gem era stata testata anche con questo strumento?
Ho visto che le validazioni vengono effettuate dalle classi /spid-0.19.0/lib/spid/saml2/*_validator.rb, ovviamente potrei integrare le validazioni mancanti, sarebbe comunque un lavoro non banale.
In base alla vostra esperienza avete messo in pratica metodi più veloci?

Grazie mille come sempre.

Saluti,

Gian Luca

**Comment by Jeanluc74** [comment]
Ho risolto il grosso delle validazioni intervenendo quasi esclusivamente su ResponseValidator, mancano all'appello 5 validazioni, di cui 3 riguardanti il confronto con il IssueInstant della Request (test 14, 39, 40 su spid-validator). Noto che ResponseValidator non ha visibilità su quel valore e quindi dovrei aggiungerlo al costruttore di Response come il request_uuid.  Potete darmi una mano in questo senso?

**Comment by Jeanluc74** [comment]
Con un po' di lavoro ho modificato il codice ancora e sono riuscito a chiudere le validazioni e a rifare i test daccapo. Se volete che contribuisca alla gem fatemi sapere.

**Comment by davidlibrera** [comment]
Ciao @Jeanluc74, scusa il ritardo nella risposta ma non avevo controllato la issue. Potresti aprire una pull request con le modifiche apportate? Almeno le mettiamo insieme. Domanda: il codice è relativo alla gemma spid-rails o a [spid-ruby](https://github.com/italia/spid-ruby)?
